export const FILTERS = [
  {
    title: "Бренд",
    query_title: "producer",
    show: true,
    checkboxList: [
      { name: "ASUS", query_value: "asus", counter: 10, active: false },
      { name: "Acer", query_value: "acer", counter: 10, active: false },
      { name: "Apple", query_value: "apple", counter: 10, active: false },
      { name: "Dell", query_value: "dell", counter: 10, active: false },
      {
        name: "HP (Hewlett Packard)",
        query_value: "hp_hewlett_packard",
        counter: 10,
        active: false,
      },
      { name: "Honor", query_value: "honor", counter: 10, active: false },
      { name: "Huawei", query_value: "huawei", counter: 10, active: false },
      { name: "Lenovo", query_value: "lenovo", counter: 10, active: false },
      { name: "MSI", query_value: "msi", counter: 10, active: false },
      {
        name: "Microsoft",
        query_value: "microsoft",
        counter: 10,
        active: false,
      },
      { name: "Samsung", query_value: "samsung", counter: 10, active: false },
      { name: "Xiaomi", query_value: "xiaomi", counter: 10, active: false },
    ],
  },
  {
    title: "Операційна система",
    query_title: "operating_system_pc",
    show: true,
    checkboxList: [
      { name: "Без ОС", query_value: "no_os", counter: 10, active: false },
      { name: "Mac OS", query_value: "mac_os", counter: 10, active: false },
      { name: "Linux", query_value: "linux", counter: 10, active: false },
      {
        name: "Windows 7",
        query_value: "windows_7",
        counter: 10,
        active: false,
      },
      {
        name: "Windows 8.x",
        query_value: "windows_8x",
        counter: 10,
        active: false,
      },
      {
        name: "Windows 10 Home",
        query_value: "windows_10_home",
        counter: 10,
        active: false,
      },
      {
        name: "Windows 11 Home",
        query_value: "windows_11_home",
        counter: 10,
        active: false,
      },
      {
        name: "Chrome OS",
        query_value: "chrome_os",
        counter: 10,
        active: false,
      },
      {
        name: "Endles OS",
        query_value: "endles_os",
        counter: 10,
        active: false,
      },
    ],
  },
  {
    title: "Процесор",
    query_title: "cpu_pc",
    show: true,
    checkboxList: [
      { name: "Apple M", query_value: "apple_m", counter: 10, active: false },
      {
        name: "Intel Celeron",
        query_value: "intel_celeron",
        counter: 10,
        active: false,
      },
      {
        name: "Intel Xeon",
        query_value: "intel_xeon",
        counter: 10,
        active: false,
      },
      {
        name: "Intel Atom",
        query_value: "intel_atom",
        counter: 10,
        active: false,
      },
      {
        name: "Intel Pentium",
        query_value: "intel_pentium",
        counter: 10,
        active: false,
      },
      {
        name: "Intel Core i3",
        query_value: "intel_core_i3",
        counter: 10,
        active: false,
      },
      {
        name: "Intel Core i5",
        query_value: "intel_core_i5",
        counter: 10,
        active: false,
      },
      {
        name: "Intel Core i7",
        query_value: "intel_core_i7",
        counter: 10,
        active: false,
      },
      {
        name: "Intel Core i9",
        query_value: "intel_core_i9",
        counter: 10,
        active: false,
      },
      { name: "AMD A", query_value: "amd_a", counter: 10, active: false },
      { name: "AMD E", query_value: "amd_e", counter: 10, active: false },
      { name: "AMD FX", query_value: "amd_fx", counter: 10, active: false },
      {
        name: "AMD Athlon",
        query_value: "amd_athlon",
        counter: 10,
        active: false,
      },
      {
        name: "AMD Ryzen 3",
        query_value: "amd_ryzen_3",
        counter: 10,
        active: false,
      },
      {
        name: "AMD Ryzen 5",
        query_value: "amd_ryzen_5",
        counter: 10,
        active: false,
      },
      {
        name: "AMD Ryzen 7",
        query_value: "amd_ryzen_7",
        counter: 10,
        active: false,
      },
      {
        name: "AMD Ryzen 9",
        query_value: "amd_ryzen_9",
        counter: 10,
        active: false,
      },
    ],
  },
];
