const option = require("../db/option");

module.exports = {
  optionsDevelop: [option.Color, option.MadeIn],
  optionsLaptop: [
    option.Producer,
    option.OperatingSystem_PC,
    option.CPU_PC,
    option.Graphics,
    option.ScreenDiagonal,
    option.TypeMemory,
    option.RAM,
    option.Color,
    option.NewUsed,
    option.Guarantee,
    option.SizeSSD,
    option.SizeHDD,
    option.MadeIn,
  ],
  optionsSmartphone: [
    option.CPU_MP,
    option.OperatingSystem_MP,
    option.RAM,
    option.TypeMatrix,
    option.Color,
    option.Guard,
    option.Guarantee,
    option.ScreenRefreshRate,
    option.Communication,
    option.BodyMaterial,
    option.MadeIn,
    option.NewUsed,
  ],
  optionsVideocards: [
    option.GraphicChip,
    option.MemoryCapacity,
    option.MemoryBusBitSize,
    option.TypeMemory_Videocards,
    option.GraphicsProcessor,
    option.Appointment,
    option.Interface_Videocards,
    option.GraphicsProcessorFamily,
    option.Connectors,
    option.Form_Factor_Videocards,
    option.MadeIn,
    option.NewUsed,
  ],
  optionsSSD: [
    option.SizeSSD,
    option.Form_Factor_Storage,
    option.Connection_Interface,
    option.Storage_Type,
    option.Appointment_Storage,
    option.Memory_Element_Type,
    option.MadeIn,
    option.NewUsed,
  ],
  optionsCPU_PC: [
    option.CPU_Family,
    option.CPU_Connector_Type,
    option.Integrated_Graphics,
    option.Number_of_Cores,
    option.Packaging_Type,
    option.CPU_Clock_Speed,
    option.CPU_Unlocked_Multiplier,
    option.CPU_Appointment,
    option.MadeIn,
    option.NewUsed,
  ],
  optionsHDD: [
    option.SizeHDD,
    option.Storage_Type,
    option.Connection_Interface,
    option.Form_Factor_Storage,
    option.Appointment_Storage,
    option.Spindle_Rotation_Speed,
    option.Technology_HDD,
    option.Buffer_Size,
    option.Color,
    option.MadeIn,
    option.NewUsed,
  ],
  optionsRAM: [
    option.RAM_Memory_Size,
    option.RAM_Memory_Type,
    option.Memory_Frequency,
    option.Number_of_Slats,
    option.Appointment_Storage,
    option.Memory_Timing_Scheme,
    option.MadeIn,
    option.NewUsed,
  ],
  optionsMotherboards: [
    option.Socket,
    option.Chipset,
    option.Memory_Support,
    option.Form_Factor_Motherboard,
    option.Embedded_Video,
    option.Video_Outputs,
    option.PCI_Express_x16,
    option.PCI_Express_x1,
    option.USB,
    option.MadeIn,
    option.NewUsed,
  ],
  optionsPSU: [
    option.Protection_Technologies,
    option.Form_Factor_PSU,
    option.Special_Properties,
    option.PSU_Type,
    option.Maximum_Noise_Level,
    option.Number_of_SATA_Connectors,
    option.Cooling_System,
    option.MadeIn,
    option.NewUsed,
  ],
  optionsCases: [
    option.Form_Factor_Motherboard,
    option.Housing_Type,
    option.Features,
    option.PSU_Location,
    option.Functionality_Connectors_Front_Panel,
    option.Color,
    option.View,
    option.Material,
    option.Installation_Method,
    option.MadeIn,
    option.NewUsed,
  ],
  optionsCoolers: [
    option.Fan_Size,
    option.Appointment_Coolers,
    option.View_Coolers,
    option.Backlight,
    option.Bearing_Type,
    option.Cooling_Type,
    option.Construction,
    option.Component_CBA,
    option.MadeIn,
    option.NewUsed,
  ],
};
