/**
 * <<< RULES >>>
 *
 * 1. The first letter of the word is capitalized
 * 2. Separator of each word "_"
 * 3. Write the words "of", "in" with a lowercase letter
 * 4. The letters of the abbreviation are all uppercase
 *
 * <<< FOR EXAMPLE >>>
 *
 * 1. Producer
 * 2. Operating_System_PC
 * 3. Made_in, Type_of_Packaging
 * 4. Component_CBA, CPU_PC, Number_of_SATA_Connectors
 */

module.exports = {
  Producer: {
    name: "Бренд",
    query_name: "producer",
    htmlElement: "select",
    select: [
      "ASUS",
      "Acer",
      "Apple",
      "Dell",
      "HP (Hewlett Packard)",
      "Honor",
      "Huawei",
      "Lenovo",
      "MSI",
      "Microsoft",
      "Samsung",
      "Xiaomi",

      // "ASUS",
      // "Acer",
      // "Apple",
      // "Dell",
      // "Gigabyte",
      // "HP",
      // "Huawei",
      // "Lenovo",
      // "MSI",
      // "Microsoft",
      // "Samsung",
      // "Xiaomi",
      // "2E",
      // "2E Gaming",
      // "AMD",
      // "AVGO",
      // "AWOW",
      // "Aero",
      // "Alien",
      // "Alienware",
      // "Alldocube",
      // "Allview",
      // "Ansta",
      // "Aorus",
      // "Archos",
      // "BMAX",
      // "Belinea",
      // "Blackview",
      // "CSL",
      // "Chuwi",
      // "Clevo",
      // "Core Innovations",
      // "CyberPower",
      // "DM",
      // "Daysky",
      // "Denver",
      // "Difinity",
      // "Digma",
      // "Dream Machines",
      // "DuoDuoGo",
      // "Durabook",
      // "Element",
      // "Eluktronics",
      // "Epic",
      // "Epik",
      // "Ergo",
      // "Evoo",
      // "Fujitsu",
      // "GOODTEL",
      // "Gateway",
      // "Getac",
      // "Google",
      // "HIRO",
      // "HPA",
      // "Haier",
      // "Honor",
      // "Hyundai",
      // "IOTA",
      // "Insys",
      // "Intel",
      // "Jepssen",
      // "Jumper",
      // "KUU",
      // "Kiano",
      // "Kruger&Matz",
      // "LG",
      // "LHMZNIY",
      // "Laptop",
      // "LincPlus",
      // "Maxcom",
      // "Meberry",
      // "Mediacom",
      // "Medion",
      // "Microtech",
      // "Millenium",
      // "Mixzo",
      // "Motile",
      // "Multicom",
      // "NEC",
      // "NiPoGi",
      // "NuVision",
      // "ONN",
      // "ORDISSIMO",
      // "Odys",
      // "Onkyo",
      // "Packard Bell",
      // "Panasonic",
      // "Pavoma",
      // "Pixus",
      // "Porsche Design",
      // "Prestigio",
      // "Prixton",
      // "Prologix",
      // "Prowise",
      // "RCA",
      // "RM",
      // "Razer",
      // "realme",
      // "SGIN",
      // "Schenker",
      // "Shinobee",
      // "Siemens",
      // "Sign",
      // "Silver",
      // "Sony",
      // "TOPOSH",
      // "Techbite",
      // "Teclast",
      // "Terra",
      // "Thomson",
      // "Toshiba",
      // "TrekStor",
      // "UTEPO",
      // "Umax",
      // "VAIO",
      // "VONO",
      // "ViewSonic",
      // "Vinga",
      // "XIDU",
      // "XMG",
      // "XPG",
      // "YASHI",
      // "Yepo",
      // "Без бренда",
    ],
    multiple: false,
  },
  Operating_System_PC: {
    name: "Операційна система",
    query_name: "operating_system_pc",
    htmlElement: "select",
    select: [
      "Без ОС",
      "Mac OS",
      "Linux",
      "Windows 7",
      "Windows 8.x",
      "Windows 10 Home",
      "Windows 11 Home",
      "Chrome OS",
      "Endles OS",
    ],
    multiple: false,
  },
  Operating_System_MP: {
    name: "Операційна система",
    query_name: "operating_system_mp",
    htmlElement: "select",
    select: [
      "Android",
      "iOS",
      "Windows Phone 8.1",
      "BlackBerry OS",
      "Harmony OS",
      "Інша",
    ],
    multiple: false,
  },
  CPU_PC: {
    name: "Процесор",
    query_name: "cpu_pc",
    htmlElement: "select",
    select: [
      "Apple M",
      "Intel Celeron",
      "Intel Xeon",
      "Intel Atom",
      "Intel Pentium",
      "Intel Core i3",
      "Intel Core i5",
      "Intel Core i7",
      "Intel Core i9",
      "AMD A",
      "AMD E",
      "AMD FX",
      "AMD Athlon",
      "AMD Ryzen 3",
      "AMD Ryzen 5",
      "AMD Ryzen 7",
      "AMD Ryzen 9",
    ],
    multiple: false,
  },
  CPU_MP: {
    name: "Процесор",
    query_name: "cpu_mp",
    htmlElement: "select",
    select: [
      "Apple A15",
      "Apple A14",
      "Apple A13",
      "Apple A12",
      "Qualcomm Snapdragon",
      "Exynos",
      "Kryo",
    ],
    multiple: false,
  },
  Graphics: {
    name: "Відеокарта",
    query_name: "graphics",
    htmlElement: "select",
    select: [
      "GeForce GTX 1050",
      "GeForce GTX 1050 Ti",
      "GeForce GTX 1650",
      "GeForce GTX 1650 Ti",
      "GeForce GTX 1660 Ti",
      "GeForce RTX 2060",
      "GeForce RTX 3050 Ti",
      "GeForce RTX 3060 Ti",
      "GeForce RTX 3070 Ti",
      "GeForce RTX 3080 Ti",
    ],
    multiple: false,
  },
  Screen_Diagonal: {
    name: "Діагональ екрана",
    query_name: "screen_diagonal",
    htmlElement: "select",
    select: ["9", "12.5", "13", "14", "15", "15.6", "16", "17", "18", "20"],
    multiple: false,
  },
  Type_Memory: {
    name: "Тип накопичувача",
    query_name: "type_memory",
    htmlElement: "select",
    select: ["HDD", "SSD", "SSD + HDD", "eMMC"],
    multiple: false,
  },
  RAM: {
    name: "Обсяг оперативної пам'яті",
    query_name: "ram",
    htmlElement: "select",
    select: [
      "Без оперативної пам'яті",
      "До 3 ГБ",
      "4 ГБ",
      "6 ГБ",
      "8 ГБ",
      "10 ГБ",
      "12 ГБ",
      "16 ГБ",
      "24 ГБ",
      "32 ГБ",
      "48 ГБ",
      "64 ГБ",
    ],
    multiple: false,
  },
  Color: {
    name: "Колір",
    query_name: "color",
    htmlElement: "select",
    select: [
      "Інші",
      "Білий",
      "Жовтий",
      "Зелений",
      "Золотий",
      "Рожевий",
      "Синій",
      "Сріблястий",
      "Сірий",
      "Фіолетовий",
      "Червоний",
      "Чорний",
      "Бежевий",
      "Блакитний",
      "Біло-золотистий",
      "Жовтогарячий",
      "Золотистий",
      "Камуфляж",
      "Сріблясто-жовтогарячий",
      "Сріблясто-чорний",
      "Сіро-зелений",
      "Темно-зелений",
      "Темно-сірий",
      "Червоно-чорний",
      "Чорний-зелений",
      "Чорно-жовтий",
      "Чорно-жовтогарячий",
      "Чорно-синій",
      "Чорно-сірий",
      "Чорно-фіолетовий",
      "Чорно-червоний",
    ],
    multiple: false,
  },
  New_Used: {
    name: "Новий - Вживаний",
    query_name: "new_used",
    htmlElement: "select",
    select: ["Новий", "Вживаний"],
    multiple: false,
  },
  Guarantee: {
    name: "Гарантія",
    query_name: "guarantee",
    htmlElement: "select",
    select: ["Немає", "1 рік", "2 роки"],
    multiple: false,
  },
  Size_SSD: {
    name: "Обсяг SSD",
    query_name: "size_ssd",
    htmlElement: "select",
    select: [
      "128 ГБ",
      "160 ГБ",
      "180 ГБ",
      "200 ГБ",
      "240 ГБ",
      "250 ГБ",
      "256 ГБ",
      "320 ГБ",
      "400 ГБ",
      "480 ГБ",
      "500 ГБ",
      "512 ГБ",
      "1 Т",
      "2 Т",
      "4 Т",
      "8 Т",
    ],
    multiple: false,
  },
  Size_HDD: {
    name: "Обсяг HDD",
    query_name: "size_hdd",
    htmlElement: "select",
    select: [
      "128 ГБ",
      "160 ГБ",
      "180 ГБ",
      "200 ГБ",
      "240 ГБ",
      "250 ГБ",
      "256 ГБ",
      "320 ГБ",
      "400 ГБ",
      "480 ГБ",
      "500 ГБ",
      "512 ГБ",
      "1 Т",
      "2 Т",
      "4 Т",
      "8 Т",
    ],
    multiple: false,
  },
  Type_Matrix: {
    name: "Тип матриці",
    query_name: "type_matrix",
    htmlElement: "select",
    select: [
      "AMOLED",
      "Dynamic AMOLED",
      "Super AMOLED",
      "Super AMOLED Plus",
      "Super AMOLED + Dynamic AMOLED 2X",
      "Fluid AMOLED",
      "Fluid AMOLED with LTPO",
      "IGZO",
      "IPS",
      "Super IPS+",
      "LCD",
      "LTPS",
      "OGS",
      "OLED",
      "TFN",
      "TN",
      "sAMOLED",
    ],
    multiple: false,
  },
  Screen_Refresh_Rate: {
    name: "Частота оновлення екрану",
    query_name: "screen_refresh_rate",
    htmlElement: "select",
    select: ["30 ГЦ", "60 ГЦ", "90 ГЦ", "120 ГЦ", "144 ГЦ", "165 ГЦ"],
    multiple: false,
  },
  Guard: {
    name: "Безпека",
    query_name: "guard",
    htmlElement: "select",
    select: [
      "Розблокування за обличчям",
      "Сканер відбитків пальця збоку",
      "Сканер відбитків пальця ззаду",
      "Сканер відбитків пальця на екрані",
    ],
    multiple: true,
  },
  Body_Material: {
    name: "Матеріал корпусу",
    query_name: "body_material",
    htmlElement: "select",
    select: ["Метал", "Пластик", "Скло", "Інший"],
    multiple: true,
  },
  Made_in: {
    name: "Країна-виробник",
    query_name: "made_in",
    htmlElement: "select",
    select: [
      "Індія",
      "В'єтнам",
      "Китай",
      "Тайвань",
      "Мексика",
      "Німеччина",
      "Польща",
      "Румунія",
      "США",
      "Словаччина",
      "Таїланд",
      "Туреччина",
      "Угорщина",
      "Україна",
      "Японія",
    ],
    multiple: false,
  },
  Communication: {
    name: "Стандарт зв'язку",
    query_name: "communication",
    htmlElement: "select",
    select: [
      "2G (GPRS/EDGE/GSM)",
      "3G (UMTS/HSUPA/HSPA/WSDMA/CDM)",
      "4G (LTE)",
      "5G",
    ],
    multiple: true,
  },
  Memory_Capacity: {
    name: "Обсяг пам'яті",
    query_name: "memory_capacity",
    htmlElement: "select",
    select: [
      "1 ГБ і менше",
      "2 ГБ",
      "3 ГБ",
      "4 ГБ",
      "5 ГБ",
      "6 ГБ",
      "8 ГБ",
      "10 ГБ",
      "11 ГБ",
      "12 ГБ",
      "16 ГБ",
      "20 ГБ",
      "24 ГБ",
      "36 ГБ",
      "48 ГБ",
      "64 ГБ",
    ],
    multiple: false,
  },
  Memory_Bus_Bit_Size: {
    name: "Розрядність шини пам'яті",
    query_name: "memory_bus_bit_size",
    htmlElement: "select",
    select: [
      "32 біт",
      "64 біт",
      "96 бітів",
      "128 біт",
      "160 біт",
      "192 біт",
      "256 біт",
      "320 біт",
      "352 біт",
      "384 біт",
      "512 біт",
      "589 біт",
      "1024 біт",
      "2048 біт",
      "4096 біт",
    ],
    multiple: false,
  },
  Type_Memory_Videocards: {
    name: "Тип пам'яті ",
    query_name: "type_memory_videocards",
    htmlElement: "select",
    select: [
      "DDR2",
      "DDR3",
      "DDR4",
      "DDR5",
      "GDDR1",
      "GDDR2",
      "GDDR3",
      "GDDR4",
      "GDDR5",
      "GDDR5X",
      "GDDR6",
      "GDDR6X",
      "HBM2",
      "LPDDR4X",
      "SDDR3",
    ],
    multiple: false,
  },
  Graphics_Processor: {
    name: "Виробник графічного процесора ",
    query_name: "graphics_processor",
    htmlElement: "select",
    select: ["AMD", "nVidia"],
    multiple: false,
  },
  Appointment: {
    name: "Призначення",
    query_name: "appointment",
    htmlElement: "select",
    select: ["Ігрові", "Для майнінгу", "Звичайні", "Професійні"],
    multiple: true,
  },
  Interface_Videocards: {
    name: "Інтерфейс",
    query_name: "interface_videocards",
    htmlElement: "select",
    select: [
      "PCI",
      "PCI Express",
      "PCI Express 1.0",
      "PCI Express 2.0",
      "PCI Express 2.1",
      "PCI Express 3.0",
      "PCI Express 4.0",
      "PCI Express 4.0 x4",
      "PCI Express x1",
      "PCI Express x4 1.x",
      "PCI Express x4 3.0",
      "PCI Express x8",
      "PCI Express x8 2.0",
      "PCI Express x8 3.0",
      "PCI Express x8 4.0",
      "PCI Express x16",
      "PCI Express x16 2.x",
      "PCI Express x16 3.0",
      "PCI Express x16 4.0",
    ],
    multiple: false,
  },
  Graphics_Processor_Family: {
    name: "Сімейство графічного процесора",
    query_name: "graphics_processor_family",
    htmlElement: "select",
    select: [
      "AMD FirePro",
      "AMD/ATI Radeon",
      "NVidia GeForce",
      "NVidia NVS",
      "NVidia Quadro",
      "NVidia RTX",
      "NVidia T",
    ],
    multiple: false,
  },
  Connector: {
    name: "Роз'єми",
    query_name: "connector",
    htmlElement: "select",
    select: [
      "DMS-59",
      "DVI",
      "DVI-D",
      "DVI-D Dual Link",
      "DVI-I",
      "DisplayPort",
      "HDMI",
      "S-Video",
      "USB Type-C",
      "VGA",
      "miniDisplayPort",
      "miniHDMI",
    ],
    multiple: true,
  },
  Form_Factor_Videocards: {
    name: "Форм-фактор Відеокарти",
    query_name: "form_factor_videocards",
    htmlElement: "select",
    select: ["Дискретна (Стандартна)", "Зовнішня", "Міні", "Низькопрофільна"],
    multiple: false,
  },
  Additional_Power_Supply: {
    name: "Додаткове живлення",
    query_name: "additional_power_supply",
    htmlElement: "select",
    select: [
      "Немає",
      "6 pin",
      "8 pin",
      "12 pin",
      "16 pin",
      "6 + 6 pin",
      "6 + 8 pin",
      "8 + 8 pin",
      "8 + 8 + 6 pin",
      "8 + 8 + 8 pin",
    ],
    multiple: false,
  },
  Cooling_System_Type: {
    name: "Тип системи охолодження",
    query_name: "cooling_system_type",
    htmlElement: "select",
    select: ["Активна", "Водяне охолодження", "Пасивна"],
    multiple: false,
  },
  Graphic_Chip: {
    name: "Графічний чип",
    query_name: "graphic_chip",
    htmlElement: "select",
    select: [
      "FirePro",
      "GeForce 210",
      "GeForce GT",
      "GeForce GT 1030",
      "GeForce GTX 1050",
      "GeForce GTX 1050 Ti",
      "GeForce GTX 1060",
      "GeForce GTX 1070",
      "GeForce GTX 1070 Ti",
      "GeForce GTX 1080",
      "GeForce GTX 1080 Ti",
      "GeForce GTX 1630",
      "GeForce GTX 1650",
      "GeForce GTX 1650 Super",
      "GeForce GTX 1660",
      "GeForce GTX 1660 Super",
      "GeForce GTX 1660 Ti",
      "GeForce GTX 560",
      "GeForce GTX 580",
      "GeForce GTX 590",
      "GeForce GTX 650",
      "GeForce GTX 660",
      "GeForce GTX 745",
      "GeForce GTX 750",
      "GeForce GTX 760",
      "GeForce GTX 770",
      "GeForce GTX 780",
      "GeForce GTX 950",
      "GeForce GTX 960",
      "GeForce GTX 970",
      "GeForce RTX 2060",
      "GeForce RTX 2060 Super",
      "GeForce RTX 2070",
      "GeForce RTX 2070 Super",
      "GeForce RTX 2080",
      "GeForce RTX 2080 Super",
      "GeForce RTX 2080 Ti",
      "GeForce RTX 3050",
      "GeForce RTX 3060",
      "GeForce RTX 3060 Ti",
      "GeForce RTX 3070",
      "GeForce RTX 3070 Ti",
      "GeForce RTX 3080",
      "GeForce RTX 3080 Ti",
      "GeForce RTX 3090",
      "GeForce RTX 3090 Ti",
      "GeForce RTX 4070 Ti",
      "GeForce RTX 4080",
      "GeForce RTX 4090",
      "NVidia CMP 90-HX (Mining)",
      "NVidia P102-100 (Mining)",
      "NVidia P104-100 (Mining)",
      "QUADRO NVS",
      "R5 220",
      "R5 230",
      "R5 430",
      "R7 240",
      "R7 250",
      "R7 360",
      "R7 370",
      "R9 270",
      "R9 270X",
      "R9 295X2",
      "R9 370",
      "R9 380",
      "RX 460",
      "RX 470",
      "RX 480",
      "RX 550",
      "RX 5500 XT",
      "RX 560",
      "RX 5600 XT",
      "RX 570",
      "RX 5700",
      "RX 5700 XT",
      "RX 580",
      "RX 590",
      "RX 6500 XT",
      "RX 6600",
      "RX 6600 XT",
      "RX 6650 XT",
      "RX 6700 XT",
      "RX 6750 XT",
      "RX 6800",
      "RX 6800 XT",
      "RX 6850M XT",
      "RX 6900 XT",
      "RX 6950 XT",
      "RX 7900 XT",
      "RX Vega 56",
      "RX Vega 64",
      "Rx​ 7900 XTX",
      "Radeon 550",
      "Radeon HD5xxx",
      "Radeon HD6xxx",
      "Radeon HD7xxx",
      "Radeon HD8xxx",
      "Radeon Pro W5500",
      "Radeon Pro W5700",
      "Radeon Pro W6600",
      "Radeon Pro W6800",
      "Radeon Pro WX 3200",
      "Radeon Pro WX 7100",
      "Radeon R5",
      "Radeon RX 5500 XT",
      "Radeon RX 5600 XT",
      "Radeon RX 6400",
      "Radeon RX 6600 XT",
      "Radeon VII",
      "Titan RTX",
      "nVidia RTX A series",
      "nVidia T series",
    ],
    multiple: false,
  },
  Form_Factor_Storage: {
    name: "Форм-фактор Накопичувача",
    query_name: "form_factor_storage",
    htmlElement: "select",
    select: [
      '1.8"',
      '2.5"',
      '3.5"',
      "Apple proprietary",
      "Half-Slim",
      "M.2",
      "PCI Express",
      "U.2",
      "mSATA",
    ],
    multiple: false,
  },
  Connection_Interface: {
    name: "Інтерфейс підключення",
    query_name: "connection_interface",
    htmlElement: "select",
    select: [
      "PCI Express",
      "SAS",
      "SATA 3.2",
      "SATAI",
      "SATAII",
      "SATAIII",
      "Thunderbolt",
      "Thunderbolt 2",
      "Thunderbolt 3",
      "USB Type-A",
      "USB Type-C",
      "mSATA",
      "Fibre Channel",
      "IDE",
      "NL-SAS (Near Line)",
      "SCSI",
      "USB 2.0",
      "USB 3.0",
      "USB 3.1",
      "USB 3.2",
      "Wi-Fi",
      "eSATA",
    ],
    multiple: false,
  },
  Storage_Type: {
    name: "Тип накопичувача",
    query_name: "storage_type",
    htmlElement: "select",
    select: ["Внутрішній", "Зовнішній"],
    multiple: false,
  },
  Appointment_Storage: {
    name: "Призначення",
    query_name: "appointment_storage",
    htmlElement: "select",
    select: ["Для комп'ютера", "Для ноутбука", "Для серверів"],
    multiple: false,
  },
  Memory_Element_Type: {
    name: "Тип елементів пам'яті",
    query_name: "memory_element_type",
    htmlElement: "select",
    select: [
      "3D NAND",
      "MLC",
      "MLC 3D NAND",
      "QLC",
      "QLC 3D NAND",
      "SLC",
      "TLC",
      "TLC 3D NAND",
      "V-NAND",
    ],
    multiple: false,
  },
  CPU_Family: {
    name: "Сімейство процесора",
    query_name: "cpu_family",
    htmlElement: "select",
    select: [
      "AMD A-Series",
      "AMD Athlon",
      "AMD EPYC",
      "AMD FX-Series",
      "AMD Opteron",
      "AMD Ryzen 3",
      "AMD Ryzen 5",
      "AMD Ryzen 7",
      "AMD Ryzen 9",
      "AMD Ryzen Threadripper",
      "Intel Celeron",
      "Intel Core 2",
      "Intel Core i3",
      "Intel Core i5",
      "Intel Core i7",
      "Intel Core i9",
      "Intel Pentium",
      "Intel Xeon Bronze",
      "Intel Xeon E",
      "Intel Xeon E3",
      "Intel Xeon E5",
      "Intel Xeon E7",
      "Intel Xeon Gold",
      "Intel Xeon Silver",
      "Intel Xeon W",
      "Intel Xeon X",
      "Phenom",
      "Sempron",
    ],
    multiple: false,
  },
  CPU_Connector_Type: {
    name: "Тип роз'єму",
    query_name: "connector_type",
    htmlElement: "select",
    select: [
      "Socket 478",
      "Socket 604",
      "Socket 754",
      "Socket 771",
      "Socket 775",
      "Socket 1150",
      "Socket 1151",
      "Socket 1151-V2",
      "Socket 1155",
      "Socket 1156",
      "Socket 1200",
      "Socket 1356",
      "Socket 1366",
      "Socket 1700",
      "Socket 2011",
      "Socket 2011-3",
      "Socket 2066",
      "Socket 3647",
      "Socket AM1",
      "Socket AM2",
      "Socket AM2+",
      "Socket AM2+/Socket AM3",
      "Socket AM3",
      "Socket AM3+",
      "Socket AM4",
      "Socket FM1",
      "Socket FM2",
      "Socket FM2+",
      "Socket H5",
      "Socket V",
      "Socket sTR4",
      "Socket sTRX4",
      "Socket sWRX8",
      "Розетка AM5",
    ],
    multiple: false,
  },
  Integrated_Graphics: {
    name: "Інтегрована графіка",
    query_name: "integrated_graphics",
    htmlElement: "select",
    select: ["Без інтегрованої графіки", "З інтегрованою графікою"],
    multiple: false,
  },
  Number_of_Cores: {
    name: "Кількість ядер",
    query_name: "number_cores",
    htmlElement: "select",
    select: [
      "1",
      "2",
      "3",
      "4",
      "6",
      "8",
      "10",
      "12",
      "14",
      "15",
      "16",
      "18",
      "20",
      "24",
      "26",
      "28",
      "32",
      "64",
    ],
    multiple: false,
  },
  Type_of_Packaging: {
    name: "Тип упаковки",
    query_name: "type_of_packaging",
    htmlElement: "select",
    select: ["BOX", "Tray"],
    multiple: false,
  },
  CPU_Clock_Speed: {
    name: "Тактова частота процесора",
    query_name: "cpu_clock_speed",
    htmlElement: "select",
    select: [
      "2.0 ГГц",
      "2.1 ГГц",
      "2.2 ГГц",
      "2.3 ГГц",
      "2.4 ГГц",
      "2.5 ГГц",
      "2.6 ГГц",
      "2.7 ГГц",
      "2.8 ГГц",
      "2.9 ГГц",
      "3.0 ГГц",
    ],
    multiple: false,
  },
  CPU_Unlocked_Multiplier: {
    name: "Розблокований помножува",
    query_name: "cpu_unlocked_multiplier",
    htmlElement: "select",
    select: ["Без розблокованого множника", "З розблокованим множником"],
    multiple: false,
  },
  CPU_Appointment: {
    name: "Призначення",
    query_name: "cpu_appointment",
    htmlElement: "select",
    select: ["Для комп'ютерів", "Для серверів"],
    multiple: false,
  },
  Spindle_Rotation_Speed: {
    name: "Швидкість обертання шпинделя",
    query_name: "spindle_rotation_speed",
    htmlElement: "select",
    select: [
      "4200 об./хв",
      "5400 об./хв",
      "5600 об/хв",
      "5700 об./хв",
      "5900 об./хв",
      "5940 об./хв",
      "7200 об./хв",
      "Понад 7200 об./хв",
    ],
    multiple: false,
  },
  Technology_HDD: {
    name: "Технологія",
    query_name: "technology_hdd",
    htmlElement: "select",
    select: ["HDD", "HDD + SSD", "SSHD (Гібридні)"],
    multiple: false,
  },
  Buffer_Size: {
    name: "Обсяг буфера",
    query_name: "buffer_size",
    htmlElement: "select",
    select: [
      "2 МБ",
      "4 МБ",
      "8 МБ",
      "16 МБ",
      "32 МБ",
      "64 МБ",
      "128 МБ",
      "256 МБ",
      "512 МБ",
    ],
    multiple: false,
  },
  RAM_Memory_Size: {
    name: "Обсяг пам'яті",
    query_name: "ram_memory_size",
    htmlElement: "select",
    select: [
      "32 МБ",
      "256 МБ",
      "512 МБ",
      "1 ГБ",
      "2 ГБ",
      "4 ГБ",
      "6 ГБ",
      "8 ГБ",
      "12 ГБ",
      "16 ГБ",
      "24 ГБ",
      "32 ГБ",
      "64 ГБ",
      "128 ГБ",
      "256 ГБ",
    ],
    multiple: false,
  },
  RAM_Memory_Type: {
    name: "Тип пам'яті",
    query_name: "ram_memory_type",
    htmlElement: "select",
    select: [
      "DDR SDRAM",
      "DDR2 SDRAM",
      "DDR3 SDRAM",
      "DDR3L SDRAM",
      "DDR4 DIMM",
      "DDR4 SDRAM",
      "DDR5 SDRAM",
      "DIMM DDR3",
      "GDDR5",
      "SODIMM DDR",
      "SODIMM DDR2",
      "SODIMM DDR3",
      "SODIMM DDR3L",
      "SODIMM DDR4",
      "SODIMM DDR5",
    ],
    multiple: false,
  },
  Memory_Frequency: {
    name: "Частота пам'яті",
    query_name: "memory_frequency",
    htmlElement: "select",
    select: [
      "133 МГц",
      "300 МГц",
      "333 МГц",
      "400 МГц",
      "533 МГц",
      "667 МГц",
      "800 МГц",
      "900 МГц",
      "1000 МГц",
      "1066 МГц",
      "1067 МГц",
      "1333 МГц",
      "1600 МГц",
      "1800 МГц",
      "1866 МГц",
      "2000 МГц",
      "2133 МГц",
      "2400 МГц",
      "2666 МГц",
      "2800 МГц",
      "2933 МГц",
      "3000 МГц",
      "3200 МГц",
      "3333 МГц",
      "3400 МГц",
      "3466 МГц",
      "3600 МГц",
      "3733 МГц",
      "3866 МГц",
      "4000 МГц",
      "4133 МГц",
      "4266 МГц",
      "4333 МГц",
      "4400 МГц",
      "4600 МГц",
      "4800 МГц",
      "5000 МГц",
      "5133 МГц",
      "5200 МГц",
      "5333 МГц",
      "5600 МГц",
      "6000 МГц",
      "6200 МГц",
      "6400 МГц",
      "7200 МГц",
      "7600 МГц",
    ],
    multiple: false,
  },
  Number_of_Slats: {
    name: "Кількість планок",
    query_name: "number_of_slats",
    htmlElement: "select",
    select: ["1", "2", "3", "4", "8"],
    multiple: false,
  },
  Memory_Timing_Scheme: {
    name: "Кількість планок",
    query_name: "memory_timing_scheme",
    htmlElement: "select",
    select: [
      "CL3",
      "CL5",
      "CL6",
      "CL7",
      "CL8",
      "CL9",
      "CL10",
      "CL11",
      "CL12",
      "CL13",
      "CL14",
      "CL15",
      "CL16",
      "CL17",
      "CL18",
      "CL19",
      "CL20",
      "CL21",
      "CL22",
      "CL30",
      "CL32",
      "CL34",
      "CL36",
      "CL38",
      "CL40",
    ],
    multiple: false,
  },
  Socket: {
    name: "Сокет",
    query_name: "socket",
    htmlElement: "select",
    select: [
      "Integrated CPU",
      "Socket 478",
      "Socket 604",
      "Socket 754",
      "Socket 771",
      "Socket 775",
      "Socket 1150",
      "Socket 1151",
      "Socket 1151-V2",
      "Socket 1155",
      "Socket 1156",
      "Socket 1200",
      "Socket 1356",
      "Socket 1366",
      "Socket 1700",
      "Socket 2011",
      "Socket 2011-3",
      "Socket 2066",
      "Socket 3647",
      "Socket AM1",
      "Socket AM2",
      "Socket AM2+",
      "Socket AM2+/Socket AM3",
      "Socket AM3",
      "Socket AM3+",
      "Socket AM4",
      "Socket FM1",
      "Socket FM2",
      "Socket FM2+",
      "Socket H5",
      "Socket V",
      "Socket sTR4",
      "Socket sTRX4",
      "Socket sWRX8",
    ],
    multiple: false,
  },
  Chipset: {
    name: "Чипсет (Північний міст)",
    query_name: "chipset",
    htmlElement: "select",
    select: [
      "AMD 690G",
      "AMD 740G",
      "AMD 760G",
      "AMD 770",
      "AMD 780",
      "AMD 785G",
      "AMD 880G",
      "AMD 970",
      "AMD A320",
      "AMD A50M",
      "AMD A520",
      "AMD A55",
      "AMD A68",
      "AMD A68H",
      "AMD A70M",
      "AMD A75",
      "AMD A88",
      "AMD A88X",
      "AMD B350",
      "AMD B450",
      "AMD B550",
      "AMD B650",
      "AMD E1-2500",
      "AMD TRX40",
      "AMD X370",
      "AMD X399",
      "AMD X470",
      "AMD X570",
      "AMD X670",
      "C612",
      "Intel 5100",
      "Intel 865G",
      "Intel 915GV",
      "Intel 945PL",
      "Intel B150",
      "Intel B250",
      "Intel B360",
      "Intel B365",
      "Intel B460",
      "Intel B560",
      "Intel B660",
      "Intel B75",
      "Intel B760",
      "Intel B85",
      "Intel C226",
      "Intel C232",
      "Intel C236",
      "Intel C242",
      "Intel C246",
      "Intel C252",
      "Intel C422",
      "Intel C600",
      "Intel C602",
      "Intel C621",
      "Intel G31",
      "Intel G41",
      "Intel H110",
      "Intel H170",
      "Intel H270",
      "Intel H310",
      "Intel H370",
      "Intel H410",
      "Intel H470",
      "Intel H510",
      "Intel H55",
      "Intel H570",
      "Intel H61",
      "Intel H610",
      "Intel H67",
      "Intel H670",
      "Intel H77",
      "Intel H770",
      "Intel H81",
      "Intel H87",
      "Intel H97",
      "Intel HM70",
      "Intel J4125",
      "Intel J5040",
      "Intel P43",
      "Intel Q270",
      "Intel Q370",
      "Intel Q43 Express",
      "Intel Q45",
      "Intel Q470",
      "Intel Q570",
      "Intel Q77",
      "Intel Q87",
      "Intel W480",
      "Intel X299",
      "Intel X58",
      "Intel X79",
      "Intel X99",
      "Intel Z170",
      "Intel Z270",
      "Intel Z370",
      "Intel Z390",
      "Intel Z490",
      "Intel Z590",
      "Intel Z68",
      "Intel Z690",
      "Intel Z77",
      "Intel Z790",
      "Intel Z87",
      "Intel Z97",
      "Intel С612",
      "Nvidia GeForce 7025",
      "SB710",
      "SoC",
      "Вбудований в APUs AMD Sempron&Athlon серій",
    ],
    multiple: false,
  },
  Memory_Support: {
    name: "Підтримка пам'яті",
    query_name: "memory_support",
    htmlElement: "select",
    select: [
      "DDR SDRAM",
      "DDR2 SDRAM",
      "DDR3 SDRAM",
      "DDR3L SDRAM",
      "DDR4 DIMM",
      "DDR4 SDRAM",
      "DDR5 SDRAM",
      "DIMM DDR3",
      "GDDR5",
      "SODIMM DDR",
      "SODIMM DDR2",
      "SODIMM DDR3",
      "SODIMM DDR3L",
      "SODIMM DDR4",
      "SODIMM DDR5",
    ],
    multiple: false,
  },
  Form_Factor_Motherboard: {
    name: "Форм-фактор Материнської плати",
    query_name: "form_factor_motherboard",
    htmlElement: "select",
    select: [
      "ATX",
      "CEB",
      "EATX",
      "EEB",
      "MicroATX",
      "MiniDTX",
      "MiniITX",
      "SBC",
      "XL-ATX",
    ],
    multiple: false,
  },
  Embedded_Video: {
    name: "Вбудоване відео",
    query_name: "embedded_video",
    htmlElement: "select",
    select: [
      "Без підтримки вбудованого відео",
      "З підтримкою відеоядра процесора",
    ],
    multiple: false,
  },
  Video_Outputs: {
    name: "Відеовиходи",
    query_name: "video_outputs",
    htmlElement: "select",
    select: ["D-Sub (VGA)", "DVI", "DisplayPort", "HDMI", "Thunderbolt"],
    multiple: true,
  },
  PCI_Express_x16: {
    name: "PCI Express x16",
    query_name: "pci_express_x16",
    htmlElement: "select",
    select: [
      "1 шт",
      "2 шт",
      "3 шт",
      "4 шт",
      "5 шт",
      "6 шт",
      "7 шт",
      "8 шт",
      "9 шт",
      "10 шт",
      "11 шт",
      "12 шт",
      "Без слота PCI Express x16",
    ],
    multiple: false,
  },
  PCI_Express_x1: {
    name: "PCI Express x1",
    query_name: "pci_express_x1",
    htmlElement: "select",
    select: [
      "1 шт",
      "2 шт",
      "3 шт",
      "4 шт",
      "5 шт",
      "6 шт",
      "7 шт",
      "8 шт",
      "9 шт",
      "10 шт",
      "11 шт",
      "12 шт",
      "Без слота PCI Express x1",
    ],
    multiple: false,
  },
  USB: {
    name: "USB",
    query_name: "usb",
    htmlElement: "select",
    select: ["USB 2.0", "USB 3.0", "USB 3.1", "USB 3.2", "USB Type-C"],
    multiple: true,
  },

  // Power Supply Unit (PSU) ==============================================================================================
  // Потужність
  // Підтримка 80 PLUS
  // Живлення материнської плати
  // Роз'єм живлення процесора
  // Кількість роз'ємів додаткового живлення для відеокарт
  // Кількість конекторів IDE (Molex)
  Protection_Technologies: {
    name: "Технології захисту",
    query_name: "protection_technologies",
    htmlElement: "select",
    select: [
      "Захист від короткого замикання (SCP)",
      "Захист від перевантаження (OLP)",
      "Захист від перевантаження (OPP)",
      "Захист від перевантаження через струм (OCP)",
      "Захист від перегрівання (OTP)",
      "Захист від перепадів напруги (OVP/UVP)",
      "Захист від стрибків струму та напруги (SIP)",
    ],
    multiple: true,
  },
  Special_Properties: {
    name: "Особливі властивості",
    query_name: "special_properties",
    htmlElement: "select",
    select: [
      "Автоматичний контроль швидкості вентилятора (AFC)",
      "Вимкнення СО у разі низького навантаження",
      "Модульне під'єднання кабелів",
      "Модульні (з відстібними дротами)",
      "Підсвітка",
    ],
    multiple: true,
  },
  Form_Factor_PSU: {
    name: "Форм-фактор БЖ",
    query_name: "form_factor_psu",
    htmlElement: "select",
    select: [
      "ATX",
      "ATX (PS/2)",
      "BTX",
      "EPS",
      "FlexATX",
      "ITX",
      "Micro ATX",
      "Mini-ITX",
      "SFX",
      "TFX",
    ],
    multiple: false,
  },
  PSU_Type: {
    name: "Тип",
    query_name: "psu_type",
    htmlElement: "select",
    select: [
      "Для геймерів",
      "Для майнінгу",
      "Зовнішній",
      "Комп'ютерний",
      "Серверний",
    ],
    multiple: true,
  },
  Maximum_Noise_Level: {
    name: "Максимальний рівень шуму, ДБ",
    query_name: "maximum_noise_level",
    htmlElement: "select",
    select: ["До 18", "18-24", "24 і більше"],
    multiple: false,
  },
  Number_of_SATA_Connectors: {
    name: "Кількість SATA роз'ємів",
    query_name: "number_of_sata_connectors",
    htmlElement: "select",
    select: ["1", "2", "3-5", "6-8", "9-11", "12-14", "15 і більше"],
    multiple: false,
  },
  Cooling_System: {
    name: "Система охолодження",
    query_name: "cooling_system",
    htmlElement: "select",
    select: ["Активна", "Пасивна"],
    multiple: false,
  },
  // Power Supply Unit (PSU) ==============================================================================================

  // Сomputer Сase ========================================================================================================
  // Кількість встановлених вентиляторів
  // Кількість внутрішніх відсіків 3.5"
  // Кількість відсіків 5.25"
  // Потужність блока живлення
  Housing_Type: {
    name: "Тип корпусу",
    query_name: "housing_type",
    htmlElement: "select",
    select: [
      "Cube Case",
      "DeskTop",
      "Fulltower",
      "HTPC",
      "Miditower",
      "Minitower",
      "Rackmount",
      "Small Form Factor",
      "Small Tower",
      "Supertower",
      "Корпус-стіл",
    ],
    multiple: false,
  },
  Features: {
    name: "Особливості",
    query_name: "features",
    htmlElement: "select",
    select: [
      "З РК екраном",
      "З безгвинтовим кріпленням",
      "З бічним вікном",
      "З вертикальним встановленням відеокарти",
      "З знімними кошиками для HDD",
      "З пиловим фільтром",
      "З підсвіткою",
      "З підтримкою СВО",
      "З системою організації кабелів",
    ],
    multiple: true,
  },
  PSU_Location: {
    name: "Розташування БЖ",
    query_name: "psu_location",
    htmlElement: "select",
    select: ["Верхнє", "Нижнє"],
    multiple: false,
  },
  Functionality_Connectors_Front_Panel: {
    name: "Функціонал і роз'єми лицьовій панелі",
    query_name: "functionality_connectors_front_panel",
    htmlElement: "select",
    select: [
      "USB 2.0",
      "USB 3.0",
      "USB 3.1",
      "USB 3.2",
      "USB Type-C",
      "eSATA",
      "Вихід для навушників",
      "Вхід для мікрофона",
      "Кардридер",
      "Керування вентиляторами",
      "Керування підсвічуванням",
    ],
    multiple: true,
  },
  View: {
    name: "Вид",
    query_name: "view",
    htmlElement: "select",
    select: [
      "Відкритий",
      "Геймерський",
      "Для майнінгу",
      "Звичайний",
      "Мультимедійний",
      "Серверний",
    ],
    multiple: false,
  },
  Material: {
    name: "Матеріал",
    query_name: "material",
    htmlElement: "select",
    select: [
      "Акрил",
      "Алюміній",
      "Гума",
      "Загартоване скло",
      "Метал",
      "Пластик",
      "Пластмаса",
      "Сталь",
    ],
    multiple: false,
  },
  Installation_Method: {
    name: "Спосіб встановлення",
    query_name: "installation_method",
    htmlElement: "select",
    select: ["Вертикальний", "Горизонтальний", "Універсальний"],
    multiple: false,
  },
  // Сomputer Сase ========================================================================================================

  // Cooling System =======================================================================================================
  // Максимальний TDP
  // Роз'єми живлення
  // Максимальний рівень шуму
  Fan_Size: {
    name: "Розмір вентилятора",
    query_name: "fan_size",
    htmlElement: "input",
    select: ["60 мм", "80 мм", "100 мм", "120 мм"],
    multiple: false,
  },
  Appointment_Coolers: {
    name: "Призначення",
    query_name: "appointment_coolers",
    htmlElement: "select",
    select: [
      "Для SSD",
      "Для відеокарт",
      "Для корпусів та БЖ",
      "Для оперативної пам'яті",
      "Для процесорів",
      "Для серверів",
    ],
    multiple: false,
  },
  View_Coolers: {
    name: "Вид",
    query_name: "view_coolers",
    htmlElement: "select",
    select: [
      "Вентилятори",
      "Компоненти систем водяного охолодження",
      "Контролери вентиляторів",
      "Кулери",
      "Пилові фільтри",
      "Радіатори",
      "Рідкий метал",
      "Системи водяного охолодження",
      "Термопаста",
      "Термопрокладки",
      "Термоінтерфейси",
      "Установчі модулі та кріплення",
    ],
    multiple: false,
  },
  Backlight: {
    name: "Підсвічування",
    query_name: "backlight",
    htmlElement: "select",
    select: [
      "ARGB",
      "RGB",
      "Без підсвітки",
      "Блакитний",
      "Білий",
      "Бірюзовий",
      "Жовтий",
      "Жовтогарячий",
      "Зелений",
      "Синій",
      "Фіолетовий",
      "Червоний",
    ],
    multiple: false,
  },
  Bearing_Type: {
    name: "Тип підшипника",
    query_name: "bearing_type",
    htmlElement: "select",
    select: [
      "Гідродинамічний підшипник (FDB)",
      "Керамічний підшипник кочення",
      "Підшипник з поліоксиметиленом (POM)",
      "Підшипник ковзання",
      "Підшипник ковзання з гвинтовою нарізкою",
      "Підшипник кочення",
      "Підшипник олійного тиску (SSO)",
      "Самозмащувальний підшипник ковзання (LDP)",
    ],
    multiple: false,
  },
  Cooling_Type: {
    name: "Тип підшипника",
    query_name: "cooling_type",
    htmlElement: "select",
    select: ["Активне", "Пасивне"],
    multiple: false,
  },
  Construction: {
    name: "Конструкція",
    query_name: "construction",
    htmlElement: "select",
    select: ["Top Flow (горизонтальна)", "Баштова"],
    multiple: false,
  },
  Component_CBA: {
    name: "Компоненти СВО",
    query_name: "component_cba",
    htmlElement: "select",
    select: [
      "Водоблоки",
      "Кріплення",
      "Помпи",
      "Радіатори",
      "Резервуари",
      "Термінали",
      "Трубки і шланги",
      "Фітинги",
      "Холодоагенти",
    ],
    multiple: false,
  },
  // Cooling System =======================================================================================================
};
