paths:
  # Login
  /api/auth/login:
    post:
      summary: Login in account
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userLoginRes"
      responses:
        200:
          description: Користувача створено.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userLoginReq"
        401:
          description: Введено не вірно пароль або пошта.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Користувача з такою поштою не знайдено.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Сталася помилка на серверові. Спробуйте пізніше.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Token:
      type: object
      required: true
        - token
      properties:
        token:
          type: string
          example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    #
    Error:
      type: object
      required: true
        - message
      properties:
        message:
          type: string
          example: Текст помилки
    #
    Success:
      type: object
      required: true
        - message
      properties:
        message:
          type: string
          example: Текст успіху
